# Generated by Django 5.0.2 on 2024-03-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name_plural': 'Api Keys'},
        ),
    ]
