# Generated by Django 5.0.2 on 2024-03-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150)),
                ('origin', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('agent', models.CharField(max_length=200)),
                ('ip', models.IntegerField()),
                ('hostname', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=30)),
                ('org', models.CharField(max_length=150)),
                ('postal', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Visits',
            },
        ),
    ]
