# Requiere la extención "REST Client"

POST http://127.0.0.1:8000/mailer/api/login
Content-Type: application/json

{ "username": "hans", "password" : "sasa2121" }

###

POST http://127.0.0.1:8000/mailer/api/signup
Content-Type: application/json

{ "username": "api", "password" : "sasa2121", "email" : "juanangelbasgall@hotmail.com" }

###

GET http://127.0.0.1:8000/mailer/api/test_token
Content-Type: application/json
Authorization: Token e262fba6c9eb8be81e24119fc7f8555f554988a5

{ "variable" : "Foo"}

###

POST http://127.0.0.1:8000/mailer/api/test_token
Content-Type: application/json
Authorization: Token e262fba6c9eb8be81e24119fc7f8555f554988a5

{ "variable" : "Foo"}
###

POST  http://127.0.0.1:8000/mailer/api/custom_mail_send
Content-Type: application/json
Authorization: Token 3ebc69310675797c97c5b55c247079cb9457984d

{
    "senderId" : 2,
    "mailTo": "juanangelbasgall@hotmail.com",
    "subject" : "Prueba7",
    "content" : "Este es un mensaje de pruebas a ver si ahora no soy tan pelotudo y llega el mensaje"
}

###

POST  http://127.0.0.1:8000/mailer/api/resend_mail_send
Content-Type: application/json
Authorization: Token 3ebc69310675797c97c5b55c247079cb9457984d

# Lamentablemente tiene que ir mi gmal al principio para que se envien los demás
{
    "senderAppName" : "Testy.com",
    "mailTo": ["juanangelbasgall@gmail.com", "juanangelbasgall@hotmail.com"],
    "subject" : "Python resend",
    "content" : "Mensaje desde el resend en python."
}